version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest-events
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - .dbdata:/var/lib/mysql

  adminer_container:
     image: adminer:latest
     environment: 
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev
     ports: 
          - 8080:8080